type Product {
  id: ID!
  title: String!
  imageUrl: String!
  description: String!
  price: Float!
  createdAt: String!
  updatedAt: String!
}

input ProductReq {
  title: String!
  imageUrl: String!
  description: String!
  price: Float!
}

type Query {
  products: [Product!]!
  product(id: Uuid!): Product
}

# type Mutation {}
