type Product {
  id: Uuid!
  title: String!
  imageUrl: String!
  description: String!
  price: Float!
  createdAt: Time!
  updatedAt: Time!
}

input ProductReq {
  title: String!
  imageUrl: String!
  description: String!
  price: Float!
}

type Query {
  products: [Product!]!
  product(id: Uuid!): Product
}

type Mutation {
  createProduct(data: ProductReq!): Product!
  updateProduct(id: Uuid!, data: ProductReq!): Product!
  deleteProduct(id: Uuid!): Boolean!
}
