type UserDto {
  id: Uuid!
  username: String!
  email: String!
  password: String!
  created_at: Time!
  updated_at: Time!
}

input UserReq {
  username: String!
  email: String!
  password: String!
}
