// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	ID     string      `json:"id"`
	Items  []*CartItem `json:"items"`
	Price  float64     `json:"price"`
	UserID string      `json:"user_id"`
}

type CartItem struct {
	ID       string  `json:"id"`
	Title    string  `json:"title"`
	ImageURL string  `json:"imageUrl"`
	Price    float64 `json:"price"`
	Count    int     `json:"count"`
}

type Product struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	ImageURL    string  `json:"imageUrl"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type ProductReq struct {
	Title       string  `json:"title"`
	ImageURL    string  `json:"imageUrl"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type Query struct {
}

type UserDto struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
