version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=shop-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"