version: "3.9"

services:

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=shop-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  tokens-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=tokens
    ports:
      - "27017:27017"

  images-db:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
