version: "3.9"

services:

  app:
    image: go-shop:local
    container_name: go-shop-app
    restart: always
    depends_on:
      - db
      - tokens-db
      - images-db
      - redis
      - grafana
      - prometheus

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=shop-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  tokens-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=tokens
    ports:
      - "27017:27017"

  images-db:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    image: redis
    container_name: go-shop-redis
    restart: always
    ports:
      - "6371:6379"
      - "16371:16379"

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"