package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"go-shop/internal/api/gql/model"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) (*model.ProductsQuery, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}
