package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"log"
	"log/slog"
	"time"

	"github.com/google/uuid"

	"go-shop/internal/api/gql/generated"
	"go-shop/internal/api/gql/model"
)

// Product is the resolver for the product field.
func (r *mutationResolver) Product(ctx context.Context) (model.ProductMutation, error) {
	return model.ProductMutation{}, nil
}

// Create is the resolver for the create field.
func (r *productMutationResolver) Create(ctx context.Context, obj *model.ProductMutation, input model.NewProduct) (*model.Product, error) {
	var updatedAt *time.Time

	newProduct, err := r.ProductsService.CreateProduct(ctx, input)
	if err != nil {
		slog.Error("%w", err)
		return nil, err
	}

	if !newProduct.CreatedAt.IsZero() {
		updatedAt = &newProduct.UpdatedAt
	}

	return &model.Product{
		ID:          newProduct.ID,
		Title:       newProduct.Title,
		ImageURL:    newProduct.ImageURL,
		Description: newProduct.Description,
		Price:       float64(newProduct.Price),
		CreatedAt:   newProduct.CreatedAt,
		UpdatedAt:   updatedAt,
	}, nil
}

// Update is the resolver for the update field.
func (r *productMutationResolver) Update(ctx context.Context, obj *model.ProductMutation, id uuid.UUID, input model.NewProduct) (*model.Product, error) {
	var updatedAt *time.Time

	product, err := r.ProductsService.UpdateProduct(ctx, id, input)
	if err != nil {
		slog.Error("%w", err)
		return nil, err
	}

	if !product.CreatedAt.IsZero() {
		updatedAt = &product.UpdatedAt
	}

	return &model.Product{
		ID:          product.ID,
		Title:       product.Title,
		ImageURL:    product.ImageURL,
		Description: product.Description,
		Price:       float64(product.Price),
		CreatedAt:   product.CreatedAt,
		UpdatedAt:   updatedAt,
	}, nil
}

// Delete is the resolver for the delete field.
func (r *productMutationResolver) Delete(ctx context.Context, obj *model.ProductMutation, id uuid.UUID) (bool, error) {
	err := r.ProductsService.DeleteProduct(ctx, id)
	if err != nil {
		return false, err
	}

	return true, err
}

// GetAll is the resolver for the get_all field.
func (r *productsQueryResolver) GetAll(ctx context.Context, obj *model.ProductsQuery) ([]*model.Product, error) {
	products, err := r.ProductsService.GetProducts(ctx)
	if err != nil {
		log.Println("%w", err)
		return nil, err
	}

	var res []*model.Product

	for _, v := range products {
		var updatedAt *time.Time

		if !v.UpdatedAt.IsZero() {
			updatedAt = &v.UpdatedAt
		}

		product := &model.Product{
			ID:          v.ID,
			Title:       v.Title,
			ImageURL:    v.ImageURL,
			Description: v.Description,
			Price:       float64(v.Price),
			CreatedAt:   v.CreatedAt,
			UpdatedAt:   updatedAt,
		}

		res = append(res, product)
	}

	return res, nil
}

// GetByID is the resolver for the get_by_id field.
func (r *productsQueryResolver) GetByID(ctx context.Context, obj *model.ProductsQuery, id uuid.UUID) (model.ProductFoundResult, error) {
	var updatedAt *time.Time

	product, err := r.ProductsService.GetProduct(ctx, id)
	if err != nil {
		log.Println("resolver: %w", err)

		return model.InternalError{Message: "internal error"}, nil
	}

	if !product.CreatedAt.IsZero() {
		updatedAt = &product.UpdatedAt
	}

	resProduct := &model.Product{
		ID:          product.ID,
		Title:       product.Title,
		ImageURL:    product.ImageURL,
		Description: product.Description,
		Price:       float64(product.Price),
		CreatedAt:   product.CreatedAt,
		UpdatedAt:   updatedAt,
	}

	return model.ProductFound{
		Product: resProduct,
	}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) (model.ProductsQuery, error) {
	return model.ProductsQuery{}, nil
}

// ProductMutation returns generated.ProductMutationResolver implementation.
func (r *Resolver) ProductMutation() generated.ProductMutationResolver {
	return &productMutationResolver{r}
}

// ProductsQuery returns generated.ProductsQueryResolver implementation.
func (r *Resolver) ProductsQuery() generated.ProductsQueryResolver { return &productsQueryResolver{r} }

type productMutationResolver struct{ *Resolver }
type productsQueryResolver struct{ *Resolver }
