type Product {
	id: Uuid!
	title: String!
	imageUrl: String!
	description: String!
	price: Float!
	createdAt: Time!
	updatedAt: Time!
}

input ProductInput {
	title: String!
	imageUrl: String!
	description: String!
	price: Float!
}

type ProductNotFound  implements ProblemInterface{
	message: String!
}